### ISSUE TITLE
Is there a way to create a single Column

### ISSUE THREAD

**Issue by hcristiano** [squareweave/wagtailcolumnblocks#11]
First off, thank you so much for this because its been a huge help and I love it. 
I am wondering if there is functionality to create a single column.
`<div class="row"><div class="col-12"></div></div>`

I have tried playing around with a few different things but nothing seems to work.

`column_1 = ColumnsBlock(
      MainBlock,
      group="Columns",
      template='template name'
  )`
Produces two columns in the admin panel
![image](https://user-images.githubusercontent.com/40251016/138351470-94bee96d-1b80-4b14-aea2-02f6907d9be9.png)

`column_1 = ColumnsBlock(
        MainBlock,
        group="Columns",
        ratios=(1, 0),
        template='standard/blocks/column/column_1.html'
    )`
Produces two columns of different sizes
![image](https://user-images.githubusercontent.com/40251016/138351701-f1dd7cb3-b118-42b1-8db2-71d8ed97143c.png)

`column_1 = ColumnsBlock(
        MainBlock,
        ratios=(1),
        group="Columns",
        template='template name'
    )` - produces an error

**Comment by stuartmaynes** [comment]
@hcristiano If you use a tuple for the ratios value then it should work.
```
ColumnsBlock( MainBlock, ratios=(1,) )
```
I suspect the error you were getting was
```
TypeError: 'int' object is not iterable
```

**Comment by hcristianowork** [comment]
@stuartmaynes lol the one thing I did not try (1,) for the ratio. Thank you so much, you have saved me :D You can close this issue!
