### ISSUE TITLE
MultiValueDictKeyError on saving a page using one of the column blocks

### ISSUE THREAD

**Issue by bruecksen** [squareweave/wagtailcolumnblocks#13]
If I try to publish a page containing one of the column blocks I get an `MultiValueDictKeyError` with `content-0-value-column_0-count` key missing. And it is right, all the columns have the same name, label, identifier: `Column 1` `column_1`. I guess this problem exists since a wagtail update. 

I'm using this package with Wagtail 2.15.5.

Anybody any leads what I could do? I tried to debug it a little but couldn't find anything - looks like the parent StructBlock of ColumnsBlock gets initialized with the correct list of name and blocks but somehow all columns have the same name and identifier.

**Comment by DominicLGit** [comment]
childblocks being passed into ColumnsBlock must be the class instead of an instance of that class

from 
`ColumnsBlock(
        ContentBlock(),
        ratios=(1, 1),
        label="Two halves",
        group="Columns",
        grid_width=12,
    )`

tp 
`ColumnsBlock(
        ContentBlock,
        ratios=(1, 1),
        label="Two halves",
        group="Columns",
        grid_width=12,
    )`

**Comment by bruecksen** [comment]
@DominicLGit thanks even a couple of years later :)
